name: CI-CD pipeline
on:
  push: 
    branches: [main]
  workflow_dispatch:


permissions: 
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3    

     
